### ISSUE TITLE
Store information of customer bookings

### ISSUE THREAD

**Issue by Navheen0508** [SupaHotBall/studio-tourism-business#4]
When customers make bookings over the phone, their bookings should be translated into the database. A text file should be used to store the information of  the bookings and the data should then be read from the file in order for it to be displayed in the system itself when required.

**Comment by Morrnc1** [comment]
## Issue: Store & Retrieve Phone Bookings

### Summary

When customers make bookings over the phone, we need a method to save these bookings into our database. The initial step involves storing these bookings in a text file, which will subsequently be read to display the booking details within the system as necessary.

### Proposed Solution

I'll create several C# classes with inheritance to facilitate this process.

**Comment by Morrnc1** [comment]
## Issue Closed: Store & Retrieve Phone Bookings

**Summary:**  
Added C# classes to handle phone bookings. Data is stored in a text file and can be displayed in the system.
